### ISSUE TITLE
U8g2lib.h - No such file or directory

### ISSUE THREAD

**Issue by Dingodadd** [Jaycar-Electronics/Morse-Trainer#1]
I keep getting the error below.
I've installed the Library, but it still occurs.

Arduino: 1.8.12 (Windows 7), Board: "Arduino Uno"

morse:5:10: fatal error: U8g2lib.h: No such file or directory

 #include <U8g2lib.h>

          ^~~~~~~~~~~

compilation terminated.

exit status 1
U8g2lib.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Jaycar-Electronics** [comment]
can you please open up "powershell" in windows, and type in:
```powershell
ls .\Documents\Arduino\libraries\ | select-string "U8" 
```
alternatively, just open up cmd and `dir Documents\Arduino\libraries`

**Comment by Dingodadd** [comment]
I have it almost working now.
I can tune it so that the the LED is flashing in time with the Morse, but the Serial Monitor is just displaying a series of E's I's and S's.

I will investigate more tomorrow.

**Comment by Jaycar-Electronics** [comment]
`E` is `.` 
`I` is `..`
`S` is `...`
By the sound of it, it might either just be getting the peaks of your audio, OR it is going perhaps too fast.. you could try slowing it down in audacity just as means to debug it.

**Comment by Jaycar-Electronics** [comment]
or try this: https://www.youtube.com/watch?v=JjDDPDdpnIM 
which was what we used in one of the images on the README.md

**Comment by Dingodadd** [comment]
I can decode that Youtube clip perfectly.
I was getting E's I's S's and H's using a Morse App on my Phone.  Perhaps it wasn't loud enough?
In any case, it appears to be working now.

**Comment by Jaycar-Electronics** [comment]
try and up / down the frequency of the tone, just to see if that helps.

EISH is all just dots, so there might be an issue with the speed of the morse.. if you can't change that in the app you might have to change the capacitors on the board,

anyway we'll close this issue as it's no longer related to Ug8lib.

regards.
